apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: An example of a Backstage application.
  annotations:
    backstage.io/code-coverage: enabled
    backstage.io/code-coverage: scm-only
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
